# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5PdUKn2kijvRdz5J3VvpbIs6vI8jRun
"""

#Q1
 #We use hash to comment

#Q2
a="Harshada"
a

#q3
a=(1,2,3)
b=list(a)
b

#4
#open a command line and type the word python followed by the path to your script file like this:python / harshada.py

#Q5
my_list = [1, 2, 3, 4, 5]
my_list[1:3]

#Q6
#(x + yj) where x and y are real numbers and j is an imaginary number
# we right in python in form of 4+5j

#Q7
age = 25
age

#Q8
price = 9.99
type(price)

#Q9
name = "Harshada"
name

#Q10
s = "Hello, World!"
s[7:12]

is_student = True
is_student = False